dist: xenial
language: python
python:
- "3.5"
- "3.6"
- "3.7"
- "3.8"
- "3.9-dev"
install:
- python3 -m pip install aiohttp
- python3 -m pip install uritemplate
- python3 -m pip install tqdm
- python3 -m pip install pydiatra pyflakes
- python3 -m pip install restructuredtext-lint
script:
- ./github-upload --help
- python3 -m pydiatra .
- python3 -m pyflakes .
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
