name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-18.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-20.04
        - python: '3.11-dev'
          os: ubuntu-20.04
          broken: broken
          # https://github.com/aio-libs/aiohttp/issues/6600 "aiohttp/_websocket.c:198:12: fatal error: longintrepr.h: No such file or directory"
          # https://github.com/aio-libs/frozenlist/issues/305 "frozenlist/_frozenlist.c:432:62: error: dereferencing pointer to incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}"
          # https://github.com/aio-libs/yarl/issues/706 "yarl/_quoting_c.c:198:12: fatal error: longintrepr.h: No such file or directory"
    runs-on: ${{matrix.os}}
    continue-on-error: ${{(matrix.broken && true) || false}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README
    - name: install deps
      run: |
        python3 -m pip install aiohttp
        python3 -m pip install uritemplate
        python3 -m pip install tqdm
    - name: smoke test
      run: |
        ./github-upload --help

# vim:ts=2 sts=2 sw=2 et
